name: Kwiki-LiveSearch
version: 0.07
abstract: Search and Display the page link on the fly!
author: Kang-min Liu (gugod@gugod.org)
license: perl
distribution_type: module
requires:
  Kwiki: 0.38
no_index:
  directory:
    - inc
generated_by: Module::Install version 0.36
